# Generated by rust2rpm 12
%bcond_without check
%global __cargo_skip_build 0

%global crate cargo-c

Name:           rust-%{crate}
Version:        0.5.1
Release:        1%{?dist}
Summary:        Helper program to build and install c-like libraries

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/cargo-c
Source:         %{crates_source}
# Initial patched metadata
# * Update cbindgen to 0.12, https://github.com/lu-zero/cargo-c/pull/47
Patch0:         cargo-c-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Helper program to build and install c-like libraries.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md
%{_bindir}/cargo-cbuild
%{_bindir}/cargo-cinstall

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Dec 19 19:13:31 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.1-1
- Initial package
